// This script controls the loading screen when clients are connecting to a co-op campaign 
// and recieving the initial campaign data from the host.

var model;
var handlers = {};

requireGW([
    'shared/gw_common'
], function(
    GW
) {
    $(document).ready(function () {
        var DEFAULT_TARGET = 'coui://ui/main/game/galactic_war/gw_play/gw_play.html?gw_campaign=1';
        var gwCampaignTarget = $.url().param('target') || DEFAULT_TARGET;
        var LOADOUT_TARGET = 'coui://ui/main/game/galactic_war/gw_coop_per_player_loadout/gw_coop_per_player_loadout.html?target=' + encodeURIComponent(gwCampaignTarget);
        // Key used in session storage to indicate which game ID is considered authoritative for the campaign state. 
        // This is used to distinguish between campaign states generated by clientside predictions/come from previous saves
        // and campaign states that came from the server's coop snapshot.
        var AUTHORITATIVE_GAME_ID_KEY = 'gw_campaign_authoritative_game_id';

        function GwCampaignLoadingViewModel() {
            var self = this;

            self.pageSubTitle = ko.observable(loc('!LOC:Connecting to co-op campaign...'));
            self.activeGameId = ko.observable().extend({ local: 'gw_active_game' });
            self.gwCampaignEnabled = ko.observable(false).extend({ session: 'gw_campaign_enabled' });
            self.gwCampaignRole = ko.observable('solo').extend({ session: 'gw_campaign_role' });
            self.reconnectToGameInfo = ko.observable().extend({ local: 'reconnect_to_game_info' });
            self.uberId = ko.observable().extend({ session: 'uberId' });
            self.displayName = ko.observable().extend({ session: 'displayName' });

            self.role = 'solo';
            self.connected = false;
            self.snapshotRequestedAt = 0;
            self.snapshotRetryHandle = undefined;
            self.navigating = false;
            self.cancelled = false;
            self.requiresLoadout = false;

            self.sendMessage = function(messageType, payload, callback) {
                if (!_.isFunction(self.send_message))
                    return;

                self.send_message(messageType, payload || {}, callback);
            };

            self.clearSnapshotRetry = function() {
                if (self.snapshotRetryHandle) {
                    clearInterval(self.snapshotRetryHandle);
                    self.snapshotRetryHandle = undefined;
                }
            };

            self.navToMainMenu = function () {
                var transitPrimaryMessage = ko.observable().extend({ session: 'transit_primary_message' });
                var transitSecondaryMessage = ko.observable().extend({ session: 'transit_secondary_message' });
                var transitDestination = ko.observable().extend({ session: 'transit_destination' });
                var transitDelay = ko.observable().extend({ session: 'transit_delay' });

                self.cancelled = true;
                self.clearSnapshotRetry();
                self.reconnectToGameInfo(undefined);

                transitPrimaryMessage(loc('!LOC:Returning to Main Menu'));
                transitSecondaryMessage('');
                transitDestination('coui://ui/main/game/start/start.html');
                transitDelay(0);
                window.location.href = 'coui://ui/main/game/transit/transit.html';
            };

            self.finishLoading = function(reason) {
                if (self.navigating || self.cancelled)
                    return;

                self.navigating = true;
                self.clearSnapshotRetry();
                self.pageSubTitle(loc('!LOC:Entering co-op campaign...'));
                console.log('[GW COOP] campaign_loading complete reason=' + reason + ' target=' + gwCampaignTarget);
                window.location.href = self.requiresLoadout ? LOADOUT_TARGET : gwCampaignTarget;
            };

            self.markAuthoritativeGameReady = function(gameId) {
                if (_.isUndefined(gameId) || gameId === null)
                    return;

                try {
                    sessionStorage.setItem(AUTHORITATIVE_GAME_ID_KEY, String(gameId));
                }
                catch (e) {
                }
            };

            self.requestSnapshot = function(reason) {
                if (self.role !== 'viewer' || self.navigating || self.cancelled)
                    return;

                var now = Date.now();
                if (now - self.snapshotRequestedAt < 750)
                    return;

                self.snapshotRequestedAt = now;
                self.pageSubTitle(loc('!LOC:Receiving co-op campaign data...'));
                console.log('[GW COOP] campaign_loading request snapshot reason=' + reason);
                self.sendMessage('request_gw_campaign_snapshot', {}, function(success, response) {
                    if (success && response && response.has_snapshot === false)
                        self.pageSubTitle(loc('!LOC:Waiting for host campaign data...'));
                });
            };

            self.ensureSnapshotRetry = function() {
                if (self.snapshotRetryHandle || self.role !== 'viewer')
                    return;

                self.snapshotRetryHandle = setInterval(function() {
                    self.requestSnapshot('retry');
                }, 1500);
            };

            self.matchesLocalClient = function(client) {
                if (!client)
                    return false;

                var localUberId = self.uberId && self.uberId();
                var localName = self.displayName && self.displayName();

                return (!_.isUndefined(localUberId) && String(client.id) === String(localUberId))
                    || (_.isString(localName) && (String(client.id) === localName || client.name === localName));
            };

            self.inferRoleFromControl = function(control) {
                if (!control)
                    return undefined;

                if (control.client && control.client.role)
                    return control.client.role;

                var localName = self.displayName && self.displayName();
                var localUberId = self.uberId && self.uberId();

                if ((!_.isUndefined(localUberId) && String(control.host_id) === String(localUberId))
                        || (_.isString(localName) && (control.host_id === localName || control.host_name === localName)))
                    return 'host';

                var connectedClients = _.isArray(control.connected_clients) ? control.connected_clients : [];
                var localClient = _.find(connectedClients, self.matchesLocalClient);
                if (localClient && localClient.role)
                    return localClient.role;

                if (_.isString(localName) && control.host_name && control.host_name !== localName)
                    return 'viewer';

                return undefined;
            };

            self.applyRole = function(role, control) {
                if (!role)
                    return;

                self.role = role;
                self.gwCampaignEnabled(true);
                self.gwCampaignRole(role);
                self.connected = true;

                if (role === 'host') {
                    self.pageSubTitle(loc('!LOC:Opening co-op campaign...'));
                    self.markAuthoritativeGameReady(self.activeGameId());
                    self.finishLoading('host_ready');
                    return;
                }

                if (role === 'viewer') {
                    var connectedClients = control && _.isArray(control.connected_clients) ? control.connected_clients : [];
                    var localClient = _.find(connectedClients, self.matchesLocalClient);
                    self.requiresLoadout = !!(localClient && localClient.requires_loadout);
                    self.pageSubTitle(loc('!LOC:Waiting for host campaign data...'));
                    self.ensureSnapshotRetry();
                    self.requestSnapshot((control && control.has_snapshot) ? 'control_has_snapshot' : 'viewer_role');
                    return;
                }

                self.finishLoading('role_' + role);
            };

            self.saveSnapshotAndEnter = function(payload) {
                if (self.navigating || self.cancelled)
                    return;

                if (!payload || !payload.snapshot || !payload.snapshot.game)
                    return;

                self.pageSubTitle(loc('!LOC:Applying co-op campaign data...'));
                self.clearSnapshotRetry();
                self.requiresLoadout = !!payload.requires_loadout;

                var hydratedGame = new GW.Game();
                hydratedGame.load(payload.snapshot.game).always(function() {
                    GW.manifest.saveGame(hydratedGame).then(function() {
                        self.activeGameId(hydratedGame.id);
                        self.markAuthoritativeGameReady(hydratedGame.id);
                        self.finishLoading('snapshot_seq_' + (payload.seq || 0));
                    }, function(err) {
                        console.error('[GW COOP] campaign_loading failed to save snapshot', err);
                        self.pageSubTitle(loc('!LOC:Failed to load co-op campaign data'));
                    });
                });
            };
        }

        model = new GwCampaignLoadingViewModel();

        handlers.server_state = function (msg) {
            if (!msg)
                return;

            var data = msg.data || {};
            var clientData = data.client || {};
            var control = clientData.control || data.control || data;
            var role = clientData.role || model.inferRoleFromControl(control);

            if (msg.state === 'gw_campaign' || msg.url === gwCampaignTarget) {
                model.applyRole(role, control);
                return;
            }

            if (msg.url && msg.url !== window.location.href) {
                window.location.href = msg.url;
                return;
            }
        };

        handlers.gw_campaign_role = function(payload) {
            if (!payload)
                return;

            model.applyRole(payload.role, payload.control);
        };

        handlers.gw_campaign_control = function(payload) {
            if (model.role === 'viewer')
                model.requestSnapshot(payload && payload.has_snapshot ? 'control_update' : 'control_wait');
        };

        handlers.gw_campaign_snapshot = function(payload) {
            console.log('[GW COOP] campaign_loading snapshot recv seq=' + (payload && payload.seq) + ' reason=' + (payload && payload.reason));
            model.saveSnapshotAndEnter(payload);
        };

        handlers.login_rejected = function () {
            console.error('GW campaign loading login rejected');
            model.navToMainMenu();
        };

        handlers.connection_disconnected = function () {
            console.error('GW campaign loading disconnected');
            model.navToMainMenu();
        };

        if (window.CommunityMods) {
            try {
                CommunityMods();
            } catch (e) {
                console.error(e);
            }
        }

        loadSceneMods('gw_campaign_loading');
        app.registerWithCoherent(model, handlers);
        ko.applyBindings(model);
        app.hello(handlers.server_state, handlers.connection_disconnected);
    });
});
